name: Release Builds
on:
  push:
    tags:
      - v3*
      - v4*
jobs:
  package_build:
    name: Build rpm/deb packages (using maven)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Import public GPG Key
        run: rpm --import release/keys/public.key
      - name: Set up the JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build the rpm
        run: mvn rpm:rpm
      - name: '📦 publish deb'
        run: |
          cd target/
          zip -r deb.package.zip . -i '*.deb'
          gh release upload ${{github.event.release.tag_name}} deb.package.zip        
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
